In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix # Confusion matrix
from sklearn.metrics import classification_report # precision, recall, f1

#from sklearn.metrics import f1_score
#from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier

In [2]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Capstone_project/cleaned_reviews.csv')
df.head()

cleaned_reviews  rating
0                                          excellent       5
1                           dog become healthy thank       5
2                     quality service everyone happy       5
3  went top dog raw food morning first time amazi...       5
4  very stylish site enough information make choi...       5

# As the data is not balanced, considering only 27398 samples for each class.



In [3]:
def get_index(x):
  
  index_1, index_2, index_3, index_4, index_5 = [], [], [], [], []
  for ind,val in enumerate(x):

    if val == 1:
      index_1.append(ind)
    elif val == 2:
      index_2.append(ind)
    elif val == 3:
      index_3.append(ind)
    elif val == 4:
      index_4.append(ind)
    else:
      index_5.append(ind)
  print(len(index_1),len(index_2), len(index_3), len(index_4), len(index_5))

  index = index_1[:27398] + index_2[:27398] + index_3[:27398] + index_4[:27398] + index_5[:27398]
  
  print(len(index))
  return index

In [4]:
index = get_index(df['rating'])

97645 27398 42016 101755 925883
136990


In [5]:
df = df.loc[index]

In [6]:
x = df.cleaned_reviews
y = df.rating

In [7]:
SEED = 2000
x_train, x_validation_and_test, y_train, y_validation_and_test = train_test_split(x, y, test_size=.25, random_state=SEED)
x_validation, x_test, y_validation, y_test = train_test_split(x_validation_and_test, y_validation_and_test, test_size=.5, random_state=SEED)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvec1 = TfidfVectorizer(max_features=100000,ngram_range=(1, 3))
tvec1.fit(x_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0,
                max_features=100000, min_df=1, ngram_range=(1, 3), norm='l2',
                preprocessor=None, smooth_idf=True, stop_words=None,
                strip_accents=None, sublinear_tf=False,
                token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
                vocabulary=None)

In [9]:
x_train_tfidf = tvec1.transform(x_train)

In [10]:
x_validation_tfidf = tvec1.transform(x_validation)

In [11]:
x_test_tfidf = tvec1.transform(x_test)

In [ ]:
# Naive Bayes 
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB()

# Training the model on the udersampled data.

clf.fit(x_train_tfidf, y_train)
# Prediction on the 
pred = clf.predict(x_validation_tfidf)
# Confusion Matrix
print(confusion_matrix(y_validation, pred))

# Precision, Recall, F1-score 
print(classification_report(y_validation, pred))

[[2219  321  287  334  314]
 [ 776 1313  574  383  350]
 [ 461  727 1039  780  426]
 [ 231  251  529 1612  780]
 [  93   81   99  325 2819]]
              precision    recall  f1-score   support

           1       0.59      0.64      0.61      3475
           2       0.49      0.39      0.43      3396
           3       0.41      0.30      0.35      3433
           4       0.47      0.47      0.47      3403
           5       0.60      0.82      0.70      3417

    accuracy                           0.53     17124
   macro avg       0.51      0.53      0.51     17124
weighted avg       0.51      0.53      0.51     17124



In [ ]:
pred_nb = clf.predict(x_test_tfidf)

print(confusion_matrix(y_test, pred_nb))

# Precision, Recall, F1-score 
print(classification_report(y_test, pred_nb))

[[2119  292  277  354  299]
 [ 778 1324  588  370  423]
 [ 433  751 1069  769  465]
 [ 210  229  544 1586  771]
 [ 104   97   98  350 2824]]
              precision    recall  f1-score   support

           1       0.58      0.63      0.61      3341
           2       0.49      0.38      0.43      3483
           3       0.41      0.31      0.35      3487
           4       0.46      0.47      0.47      3340
           5       0.59      0.81      0.68      3473

    accuracy                           0.52     17124
   macro avg       0.51      0.52      0.51     17124
weighted avg       0.51      0.52      0.51     17124



In [ ]:
from sklearn.linear_model import LogisticRegression
clf_lr = LogisticRegression(max_iter=500)
clf_lr.fit(x_train_tfidf, y_train)
pred_lr = clf.predict(x_validation_tfidf)
# Confusion Matrix
print(confusion_matrix(y_validation, pred_lr))

# Precision, Recall, F1-score 
print(classification_report(y_validation, pred_lr))

[[2219  321  287  334  314]
 [ 776 1313  574  383  350]
 [ 461  727 1039  780  426]
 [ 231  251  529 1612  780]
 [  93   81   99  325 2819]]
              precision    recall  f1-score   support

           1       0.59      0.64      0.61      3475
           2       0.49      0.39      0.43      3396
           3       0.41      0.30      0.35      3433
           4       0.47      0.47      0.47      3403
           5       0.60      0.82      0.70      3417

    accuracy                           0.53     17124
   macro avg       0.51      0.53      0.51     17124
weighted avg       0.51      0.53      0.51     17124

