In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


In [ ]:
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/Capstone_project/cleaned_reviews.csv')
df.head()

cleaned_reviews  rating
0                                          excellent       5
1                           dog become healthy thank       5
2                     quality service everyone happy       5
3  went top dog raw food morning first time amazi...       5
4  very stylish site enough information make choi...       5

In [ ]:
df= df.rename(columns={"cleaned_reviews": "comment", "rating": "rating"})

In [ ]:
df = df[['comment','rating']]
df.head()

comment  rating
0                                          excellent       5
1                           dog become healthy thank       5
2                     quality service everyone happy       5
3  went top dog raw food morning first time amazi...       5
4  very stylish site enough information make choi...       5

Mapping classes from 5 --> 3

In [ ]:
def get_index(x):
  
  index_1,index_2,index_3,index_4,index_5 = [], [], [], [], []
  for ind,val in enumerate(x):

    if val == 1:
      index_1.append(ind)
    #elif val == 2:
     # index_2.append(ind)
    elif val == 3:
      index_3.append(ind)
    #elif val == 4:
     # index_4.append(ind)
    elif val == 5:
      index_5.append(ind)
  print(len(index_1),len(index_3),len(index_5))

  index = index_1[:len(index_3)] + index_3[:] + index_5[:len(index_3)]
  print(len(index))
  return index

In [ ]:
index = get_index(df['rating'])

97645 42016 925883
126048


In [ ]:
df_train= df.loc[index]

In [ ]:
X = df_train.comment
y = df_train.rating

Train-Test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
X_train = [s.lower() for s in X_train]
print(len(X_train))
print(X_train[:2])

84452
['good experience petswag product not available promised good communication regarding late shipment appreciated would business ordered car safety harness clickit tried yet judging great review work great', 'loved website bulk option let order without personal agent setting account came freaking fast']


In [ ]:
X_test = [s.lower() for s in X_test]
print(len(X_test))
print(X_test[:2])

41596
['very responsive twitter costumer service shipment delayed no response email contact soon messaged twitter emma touch solved issue immediately wish contacted twitter sooner', 'tried time touch order not arrived no response previously stated no telephone number customer service non existent']


In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

Tokenizing the data, will be fitting on training set only. This will create vocabulary on training data. 

Tokenization is done using character level, characters a-z

In [ ]:
# Initialization
tk = Tokenizer(num_words=None, char_level=True, oov_token='UNK')
# Fitting
tk.fit_on_texts(X_train)

In [ ]:
# List the vocabulary
print(tk.word_index)
print(len(tk.word_index))

{'UNK': 1, ' ': 2, 'e': 3, 'r': 4, 'o': 5, 't': 6, 'a': 7, 'i': 8, 'n': 9, 'l': 10, 's': 11, 'd': 12, 'c': 13, 'p': 14, 'u': 15, 'm': 16, 'g': 17, 'y': 18, 'h': 19, 'v': 20, 'w': 21, 'f': 22, 'k': 23, 'b': 24, 'x': 25, 'q': 26, 'z': 27, 'j': 28}
28


Each sentence is converted based on tokens

In [ ]:
sequences = tk.texts_to_sequences(X_train)
print(X_train[0])
print(sequences[0])

good experience petswag product not available promised good communication regarding late shipment appreciated would business ordered car safety harness clickit tried yet judging great review work great
[17, 5, 5, 12, 2, 3, 25, 14, 3, 4, 8, 3, 9, 13, 3, 2, 14, 3, 6, 11, 21, 7, 17, 2, 14, 4, 5, 12, 15, 13, 6, 2, 9, 5, 6, 2, 7, 20, 7, 8, 10, 7, 24, 10, 3, 2, 14, 4, 5, 16, 8, 11, 3, 12, 2, 17, 5, 5, 12, 2, 13, 5, 16, 16, 15, 9, 8, 13, 7, 6, 8, 5, 9, 2, 4, 3, 17, 7, 4, 12, 8, 9, 17, 2, 10, 7, 6, 3, 2, 11, 19, 8, 14, 16, 3, 9, 6, 2, 7, 14, 14, 4, 3, 13, 8, 7, 6, 3, 12, 2, 21, 5, 15, 10, 12, 2, 24, 15, 11, 8, 9, 3, 11, 11, 2, 5, 4, 12, 3, 4, 3, 12, 2, 13, 7, 4, 2, 11, 7, 22, 3, 6, 18, 2, 19, 7, 4, 9, 3, 11, 11, 2, 13, 10, 8, 13, 23, 8, 6, 2, 6, 4, 8, 3, 12, 2, 18, 3, 6, 2, 28, 15, 12, 17, 8, 9, 17, 2, 17, 4, 3, 7, 6, 2, 4, 3, 20, 8, 3, 21, 2, 21, 5, 4, 23, 2, 17, 4, 3, 7, 6]


In [ ]:
sequences_test = tk.texts_to_sequences(X_test)
print(X_test[0])
print(sequences_test[0])

very responsive twitter costumer service shipment delayed no response email contact soon messaged twitter emma touch solved issue immediately wish contacted twitter sooner
[20, 3, 4, 18, 2, 4, 3, 11, 14, 5, 9, 11, 8, 20, 3, 2, 6, 21, 8, 6, 6, 3, 4, 2, 13, 5, 11, 6, 15, 16, 3, 4, 2, 11, 3, 4, 20, 8, 13, 3, 2, 11, 19, 8, 14, 16, 3, 9, 6, 2, 12, 3, 10, 7, 18, 3, 12, 2, 9, 5, 2, 4, 3, 11, 14, 5, 9, 11, 3, 2, 3, 16, 7, 8, 10, 2, 13, 5, 9, 6, 7, 13, 6, 2, 11, 5, 5, 9, 2, 16, 3, 11, 11, 7, 17, 3, 12, 2, 6, 21, 8, 6, 6, 3, 4, 2, 3, 16, 16, 7, 2, 6, 5, 15, 13, 19, 2, 11, 5, 10, 20, 3, 12, 2, 8, 11, 11, 15, 3, 2, 8, 16, 16, 3, 12, 8, 7, 6, 3, 10, 18, 2, 21, 8, 11, 19, 2, 13, 5, 9, 6, 7, 13, 6, 3, 12, 2, 6, 21, 8, 6, 6, 3, 4, 2, 11, 5, 5, 9, 3, 4]


Setting the length to 1014 using post padding

In [ ]:
data = pad_sequences(sequences, maxlen=1014, padding='post')
data_test = pad_sequences(sequences_test, maxlen=1014, padding='post')

Convert into numpy array

In [ ]:
data = np.array(data)
data_test = np.array(data_test)
print(data.shape) # All sentence length are 1014
print(data_test.shape)

(84452, 1014)
(41596, 1014)


In [ ]:
class_list = y_train
class_list_test = y_test
print(set(class_list),set(class_list_test))
print(len(class_list)) # how many length
print(class_list[:10]) # print top 10 samples classes

{1, 3, 5} {1, 3, 5}
84452
32526      5
26405      5
1049832    3
36817      1
488989     1
10943      5
477671     1
241515     1
49206      5
28833      1
Name: rating, dtype: int64


Reducing classes to 0,1,2

In [ ]:
def mapp(l):
  m_list=[]
  for i,val in enumerate(l):
    if val == 1:
      m_list.append(0)
    elif val == 3:
      m_list.append(1)
    else:
      m_list.append(2)
  return m_list

In [ ]:
class_list = mapp(class_list) # change index from [1, 3, 5] to [0, 1, 2] in order to use to_categorical()
class_list_test = mapp(class_list_test)
print(set(class_list))
print(set(class_list_test)) 
print(class_list[:5]) # print top 5 samples classes to comfirm the changes
print(class_list_test[:5])

{0, 1, 2}
{0, 1, 2}
[2, 2, 1, 0, 0]
[1, 0, 1, 1, 2]


Creating one-hot representation of target variables

In [ ]:
from tensorflow.keras.utils import to_categorical
classes_train = to_categorical(class_list)
classes_test = to_categorical(class_list_test)
print(classes_train[:10])
class_list=None
class_list_test=None

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
vocab_size = len(tk.word_index)
vocab_size

28

Creating Embedded weights of 71*70 

In [ ]:
embedding_weights = [] #(71, 70)
embedding_weights.append(np.zeros(vocab_size)) # first row is pad

for char, i in tk.word_index.items(): # from index 1 to 70
    onehot = np.zeros(vocab_size)
    onehot[i-1] = 1
    embedding_weights.append(onehot)
embedding_weights = np.array(embedding_weights)

In [ ]:
print(embedding_weights.shape) # first row all 0 for PAD, 69 char, last row for UNK
embedding_weights

(29, 28)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0

We are using 1D CNN with emdedded layer, maxpooling layer and dropout

In [ ]:
from tensorflow.keras.layers import Input, Embedding, Activation, Flatten, Dense
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dropout
from tensorflow.keras.models import Model

Setting the filter size, input/output dimensions.

In [ ]:
# parameter 
input_size = 1014
# vocab_size = 69
embedding_size = vocab_size
conv_layers = [[256, 7, 3], 
               [256, 7, 3], 
               [256, 3, -1], 
               [256, 3, -1], 
               [256, 3, -1], 
               [256, 3, 3]]

fully_connected_layers = [1024, 1024]
num_of_classes = 3
dropout_p = 0.5
optimizer = 'adam'
loss = 'categorical_crossentropy'

In [ ]:
# Embedding layer Initialization
embedding_layer = Embedding(vocab_size+1, 
                            embedding_size,
                            input_length=input_size,
                            weights=[embedding_weights])

In [ ]:

# Input
inputs = Input(shape=(input_size,), name='input', dtype='int64')  # shape=(?, 1014)
# Embedding 
x = embedding_layer(inputs)
# Conv 
for filter_num, filter_size, pooling_size in conv_layers:
    x = Conv1D(filter_num, filter_size)(x) 
    x = Activation('relu')(x)
    if pooling_size != -1:
        x = MaxPooling1D(pool_size=pooling_size)(x) # Final shape=(None, 34, 256)
x = Flatten()(x) # (None, 8704)
# Fully connected layers 
for dense_size in fully_connected_layers:
    x = Dense(dense_size, activation='relu')(x) # dense_size == 1024
    x = Dropout(dropout_p)(x)
# Output Layer
predictions = Dense(num_of_classes, activation='softmax')(x)
# Build model
model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer=optimizer, loss=loss, metrics=['accuracy']) # Adam, categorical_crossentropy
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           [(None, 1014)]            0         
_________________________________________________________________
embedding (Embedding)        (None, 1014, 28)          812       
_________________________________________________________________
conv1d (Conv1D)              (None, 1008, 256)         50432     
_________________________________________________________________
activation (Activation)      (None, 1008, 256)         0         
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, 336, 256)          0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 330, 256)          459008    
_________________________________________________________________
activation_1 (Activation)    (None, 330, 256)         

In [ ]:
# Training
model.fit(data, classes_train,
          validation_data=(data_test, classes_test),
          batch_size=128,
          epochs=6,
          verbose=2)

Epoch 1/6
660/660 - 59s - loss: 0.9005 - accuracy: 0.5586 - val_loss: 0.7812 - val_accuracy: 0.6426
Epoch 2/6
660/660 - 61s - loss: 0.7403 - accuracy: 0.6754 - val_loss: 0.7105 - val_accuracy: 0.6864
Epoch 3/6
660/660 - 63s - loss: 0.6883 - accuracy: 0.7049 - val_loss: 0.6985 - val_accuracy: 0.6948
Epoch 4/6
660/660 - 62s - loss: 0.6468 - accuracy: 0.7262 - val_loss: 0.7175 - val_accuracy: 0.6853
Epoch 5/6
660/660 - 63s - loss: 0.6088 - accuracy: 0.7463 - val_loss: 0.7889 - val_accuracy: 0.6706
Epoch 6/6
660/660 - 63s - loss: 0.5666 - accuracy: 0.7667 - val_loss: 0.7469 - val_accuracy: 0.6847


# We get an accuracy of 68%

# Trying to see how logistic regression works on the data 

In [ ]:
### After split

In [ ]:
def mapp(l):
  m_list=[]
  for i,val in enumerate(l):
    if val == 1 :
      m_list.append(0)
    elif val == 3:
      m_list.append(1)
    else:
      m_list.append(2)
  return m_list

In [ ]:
y_train = mapp(y_train)
y_test = mapp(y_test)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvec1 = TfidfVectorizer(max_features=10000,ngram_range=(1, 3))
tvec1.fit(X_train)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=10000,
                min_df=1, ngram_range=(1, 3), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [ ]:
X_train = tvec1.transform(X_train)
X_test = tvec1.transform(X_test)

In [ ]:
y_train = np.array(y_train)
y_test = np.array(y_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix # Confusion matrix
from sklearn.metrics import classification_report # precision, recall, f1

In [ ]:
clf_lr = LogisticRegression(max_iter=300)
print(clf_lr)
clf_lr.fit(X_train, y_train)
pred_lr = clf_lr.predict(X_test)

print(confusion_matrix(y_test, pred_lr))

# Precision, Recall, F1-score 
print(classification_report(y_test, pred_lr))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=300,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
[[ 9436  2840  1639]
 [ 2470  9243  2172]
 [  603  1458 11735]]
              precision    recall  f1-score   support

           0       0.75      0.68      0.71     13915
           1       0.68      0.67      0.67     13885
           2       0.75      0.85      0.80     13796

    accuracy                           0.73     41596
   macro avg       0.73      0.73      0.73     41596
weighted avg       0.73      0.73      0.73     41596



# Logistic Regression gives 73% accuracy.